### ISSUE TITLE
23.08 branch

### ISSUE THREAD

**Issue by tim77** [flathub/org.freedesktop.Platform.VulkanLayer.MangoHud#31]
Please branch new `23.08`. `com.valvesoftware.Steam` already switched to new freedesktop 23.08 runtime.

**Comment by okseb** [comment]
Yes please due to the mismatch MangoHud is unusable to anyone who keeps their system updated.

**Comment by gasinvein** [comment]
Pushed 6bcf5143f98be0ca16703321ce7ffd73e66a4cd2, should be available soon.

@barthalion can you please make the branch `branch/23.08` default?

**Comment by okseb** [comment]
I installed the new 23.08 based version and it's not loading into any games can anyone else confirm?

**Comment by HanPrower** [comment]
I can confirm that it's not working after the update...

Prodding `mangohud` returns an error
```
flatpak run --command="mangohud" --file-forwarding com.valvesoftware.Steam
bwrap: execvp mangohud: No such file or directory
```

Prodding the full path shows it works, so I guess it's a PATH issue somehow?
```
flatpak run --command="/usr/lib/extensions/vulkan/MangoHud/bin/mangohud" --file-forwarding com.valvesoftware.Steam
ERROR: No program supplied

Usage: mangohud <program>
```

I assume this is more a Flatpak Steam problem than a problem of this package, but I don't see an obvious commit that may have broken these sorts of extensions from working.

**Comment by okseb** [comment]
<s>Ok so weird development, so as I began investigating by running Steam from the terminal I see it loading and reading the conf file normally. So I thought maybe somehow MangoHud is not able to see the keyboard shortcuts anymore (because I run no-display which hides MangoHud by default) so I commented that out and MangoHud is in fact loading/visible. It just can't be toggled with the default shortcut Shift+F12 anymore oddly.</s>

@HanPrower btw I use MANGOHUD=1 as an env variable on Steam through Flatseal

Edit: nvm it isn't working, I got confused as I was testing Valheim that last attempt as it loads quickly (previously was testing with Dead Space). Valheim is a native Linux title so the issue is that for some reason MangoHud is no longer working in Proton titles.

**Comment by gasinvein** [comment]
Does it work for _native_ Vulkan games, with `MANGOHUD=1`?

**Comment by tim77** [comment]
> Does it work for _native_ Vulkan games, with `MANGOHUD=1`?

Doesn’t work with native Vulkan games. Tested on Quake II Remastered.
EDIT: game using natively Vulkan but run via Proton (official Valve build).

**Comment by tim77** [comment]
```
DEBUG:root:Addding /usr/lib/extensions/vulkan/gamescope/bin to PATH
DEBUG:root:Addding /usr/lib/extensions/vulkan/MangoHud/bin to PATH
```

**Comment by tim77** [comment]
What i found is that MangoHud works fine with `com.valvesoftware.Steam.CompatibilityTool.Proton` community build. MangoHud doesn’t work only with official Proton, so something pressure-vessel related i guess.

**Comment by gasinvein** [comment]
So for some reason vulkan-loader inside the Steam Runtime container isn't picking up the flatpak'ed Vulkan layers. And for some reason it broke only on fd.o sdk 23.08?
Maybe @nanonyme or @smcv has any idea what may be going on here?

**Comment by smcv** [comment]
> So for some reason vulkan-loader inside the Steam Runtime container isn't picking up the flatpak'ed Vulkan layers. And for some reason it broke only on fd.o sdk 23.08? Maybe @nanonyme or @smcv has any idea what may be going on here?

Please open an issue in https://github.com/ValveSoftware/steam-runtime with steps to reproduce and I'll try to take a look.

**Comment by barthalion** [comment]
> Pushed [6bcf514](https://github.com/flathub/org.freedesktop.Platform.VulkanLayer.MangoHud/commit/6bcf5143f98be0ca16703321ce7ffd73e66a4cd2), should be available soon.
> 
> @barthalion can you please make the branch `branch/23.08` default?

Done
